services:
  blog-backend:
    image: ghcr.io/yu-pengy/blog-backend:latest
    container_name: blog-backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - blog-network

  blog-frontend:
    image: ghcr.io/yu-pengy/blog-frontend:latest
    container_name: blog-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - blog-backend
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge